version: "3.9"

services:
  prestashop:
    image: qaziok/potential-train
    depends_on:
      - mariadb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
    environment:
      - DISABLE_MAKE=0
      - PS_DEV_MODE=0
      - PS_DEMO_MODE=0
      - DB_SERVER=mariadb
      - DB_NAME=prestashop
      - DB_PORT=3306
      - DB_PASSWD=prestashop
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=localhost
      - PS_LANGUAGE=pl
      - PS_COUNTRY=PL
      - PS_FOLDER_ADMIN=admin-panel
      - PS_ENABLE_SSL=1
      - ADMIN_MAIL=admin@admin.pl
      - ADMIN_PASSWD=admin123
    ports:
      - 18467:443
    networks:
      - potential-train

  mariadb:
    image: mariadb
    environment:
      - MYSQL_DATABASE=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
    networks:
      - potential-train

networks:
  potential-train:
