version: "3.9"

services:
  prestashop:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}

    container_name: prestashop
    depends_on:
      - mariadb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s
    environment:
      - DISABLE_MAKE=0
      - PS_DEV_MODE=0
      - PS_DEMO_MODE=0
      - DB_SERVER=mariadb
      - DB_PASSWD=prestashop
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=localhost
      - PS_LANGUAGE=pl
      - PS_COUNTRY=PL
      - PS_FOLDER_ADMIN=admin-panel
      - PS_ENABLE_SSL=1
      - ADMIN_MAIL=admin@admin.pl
      - ADMIN_PASSWD=admin123
    ports:
      - 4433:443

  mariadb:
    image: mariadb
    container_name: prestashop-db
    environment:
      - MYSQL_DATABASE=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
    volumes:
      - ./docker/ssl/sql:/docker
      - ./docker/db:/docker-entrypoint-initdb.d:ro
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 140s

  adminpanel:
    image: phpmyadmin
    container_name: prestashop-adminpanel
    depends_on:
      - mariadb
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=localhost
      - PMA_PORT=3306
    ports:
      - 8081:80
