version: '3.9'

services:

  mariadb:
    image: mariadb
    container_name: prestashop-db
    environment:
      - MYSQL_DATABASE=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
    networks:
      - prestashop

  prestashop:
    image: prestashop/prestashop:1.7
    container_name: prestashop
    depends_on:
      - mariadb
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=mariadb
      - DB_USER=root
      - DB_PASSWD=prestashop
      - PS_INSTALL_AUTO=0
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./src:/var/www/html
      - ./src/modules:/var/www/html/modules
      - ./src/themes:/var/www/html/themes
      - ./src/override:/var/www/html/override
    networks:
      - prestashop

networks:
  prestashop: