version: "3.9"

services:
  prestashop:
    image: prestashop/prestashop
    container_name: prestashop
    depends_on:
      - mariadb
    environment:
      - PS_DEV_MODE=1
      - DB_SERVER=mariadb
      - DB_PASSWD=prestashop
      - PS_INSTALL_AUTO=1
      - PS_DOMAIN=localhost
      - PS_LANGUAGE=pl
      - PS_COUNTRY=PL
      - PS_FOLDER_ADMIN=admin-panel
      - PS_ENABLE_SSL=1
      - ADMIN_MAIL=admin@admin.pl
      - ADMIN_PASSWD=admin123
    ports:
      - 8080:80
      - 4433:443
    volumes:
      - ./src:/var/www/html
      - ./docker/ssl/apache2:/docker

  mariadb:
    image: mariadb
    container_name: prestashop-db
    environment:
      - MYSQL_DATABASE=prestashop
      - MYSQL_ROOT_PASSWORD=prestashop
    volumes:
      - ./docker/ssl/sql:/docker
      - ./docker/db:/docker-entrypoint-initdb.d

  adminpanel:
    image: phpmyadmin
    container_name: prestashop-adminpanel
    depends_on:
      - mariadb
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=localhost
      - PMA_PORT=3306
    ports:
      - 8081:80
